services:

  postgres:
    image: postgres:15
    container_name: ticket-postgres
    environment:
      POSTGRES_DB: ticketdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data

  nestjs:
    build: ./server
    container_name: ticket-nestjs
    ports:
      - "3000:3000"
    environment:
      DATABASE_URL: postgres://postgres:postgres@postgres:5432/ticketdb
      SPRING_WORKFLOW_URL: http://springboot:8080/spring/
    depends_on:
      - postgres

  springboot:
    build: ./BackendTicketSupport
    container_name: ticket-spring
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/ticketdb
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
    depends_on:
      - postgres

  frontend:
    build: ./client
    container_name: ticket-frontend
    ports:
      - "5173:80"
    depends_on:
      - nestjs

volumes:
  postgres_data:
