name: CI + CD Pipeline

on:
  push:
    branches: [main]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Checkout code
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2️⃣ Setup Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      # 3️⃣ Setup Java
      - name: Setup Java 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      # 4️⃣ Build Frontend
      - name: Build Frontend
        working-directory: client
        run: |
          npm ci
          npm run build

      # 5️⃣ Build NestJS
      - name: Build NestJS
        working-directory: server
        run: |
          npm ci
          npm run build

      # 6️⃣ Build Spring Boot
      - name: Build Spring Boot
        working-directory: BackendTicketSupport
        run:
          mvn clean package -DskipTests


  

      # 7️⃣ Docker Hub Login (CD starts here)
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # 8️⃣ Build & Push Docker Images
      - name: Build & Push Images
        run: |
          docker build -t hatemsf/ticket-frontend:latest ./client
          docker build -t hatemsf/ticket-nestjs:latest ./server
          docker build -t hatemsf/ticket-spring:latest ./BackendTicketSupport

          docker push hatemsf/ticket-frontend:latest
          docker push hatemsf/ticket-nestjs:latest
          docker push hatemsf/ticket-spring:latest
